---
<<: !include _common-esphome.yml
esp8266:
  board: d1_mini

substitutions:
  devicename: smartmeter
  wifi_ip: 192.168.1.50

uart:
  id: uart_bus
  tx_pin: TX
  rx_pin: RX
  baud_rate: 115200

dsmr:
  uart_id: uart_bus

sensor:
  - platform: dsmr
    energy_delivered_tariff1:
      name: Power consumption low
      on_value:
        then:
          - switch.turn_on: led
          - delay: 100ms
          - switch.turn_off: led
    energy_delivered_tariff2:
      name: Power consumption normal
      on_value:
        then:
          - switch.turn_on: led
          - delay: 100ms
          - switch.turn_off: led
    energy_returned_tariff1:
      name: Power production low
    energy_returned_tariff2:
      name: Power production normal
    power_returned:
      name: Actual production
    power_delivered:
      name: Actual consumption
    gas_delivered:
      name: Gas consumption

switch:
  - platform: gpio
    pin: D5
    id: led
