---
<<: !include _common-esphome.yml
esp32:
  board: esp32doit-devkit-v1


substitutions:
  devicename: baecon
  wifi_ip: 192.168.1.51

esp32_ble_tracker:
  scan_parameters:
    active: false  # not needed and consumes more power

binary_sensor:
  - platform: ble_presence
    device_class: occupancy
    ibeacon_uuid: !secret wilmar_ble_ibeacon_uuid
    name: Wilmar Phone Cupboard

  - platform: ble_presence
    device_class: occupancy
    ibeacon_uuid: !secret annemarie_ble_ibeacon_uuid
    name: Annemarie Phone Cupboard
