---
<<: !include _common-esp32.yml

# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.51
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Esphome setup
esphome:
  name: baecon
  platform: ESP32
  board: esp32doit-devkit-v1

esp32_ble_tracker:

binary_sensor:
  - platform: ble_presence
    device_class: occupancy
    mac_address: !secret wilmar_ble_mac
    name: Wilmar Cupboard

  - platform: ble_presence
    device_class: occupancy
    mac_address: !secret annemarie_ble_mac
    name: Annemarie Cupboard

sensor:
  - platform: ble_rssi
    mac_address: !secret wilmar_ble_mac
    accuracy_decimals: 0
    unit_of_measurement: "%"
    icon: "mdi:battery-bluetooth"
    # Convert to positive values
    filters:
      multiply: -1
    name: "Wilmar Tracker Battery"
  - platform: ble_rssi
    mac_address: !secret annemarie_ble_mac
    unit_of_measurement: "%"
    accuracy_decimals: 0
    icon: "mdi:battery-bluetooth"
    # Convert to positive values
    filters:
      multiply: -1
    name: "Annemarie Tracker Battery"
