---
<<: !include _common-esp8266.yml

# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.52
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Esphome setup
esphome:
  name: tv_remote
  platform: ESP8266
  board: d1_mini

# Modules setup
remote_transmitter:
  pin:
    number: D7
  carrier_duty_percent: 50%

switch:
  # TV Power Button with state from CT Clamp
  - platform: template
    name: TV Power Button
    icon: "mdi:television"
    restore_state: true
    # 0.02288 A: idle consumption
    lambda: |
      if (id(tv_clamp).state > 0.025) {
          return true;
      } else {
        return false;
      }
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
          repeat:
            times: 3
            wait_time: 200ms
    turn_off_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E040BF
          repeat:
            times: 3
            wait_time: 200ms

  # TV Source button
  - platform: template
    name: TV Source Button
    icon: "mdi:television-guide"
    turn_on_action:
      - remote_transmitter.transmit_samsung:
          data: 0xE0E0807F

# CT Clamp sensor to check if the TV is really on
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    id: tv_clamp
    update_interval: 1s
    accuracy_decimals: 4
    internal: true

  - platform: adc
    pin: A0
    id: adc_sensor
    internal: true
