---
<<: !include _common-esp8266.yml
<<: !include _common-blind.yml

substitutions:
  devicename: bedroom_blind
  upper_devicename: Bedroom Blind
  mystepper: my_stepper  # Name of the stepper motor (leave as is)
  speed: 1000 steps/s  # Set the speed of the motor

# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.53
    gateway: 192.168.1.1
    subnet: 255.255.255.0

web_server:
  port: 80
