---
<<: !include _common-esphome.yml
esp8266:
  board: d1_mini

substitutions:
  devicename: stove
  wifi_ip: 192.168.1.54

# Modules setup
binary_sensor:
  # TV Power Button with state from CT Clamp
  - platform: template
    name: Stove
    # starting the cooker hood +/- 0.31V (0.01A)
    lambda: |
      if (id(stove_clamp).state > 0.04) {
          return true;
      } else {
        return false;
      }

# CT Clamp sensor to check if the stove is on
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    id: stove_clamp
    update_interval: 10s
    accuracy_decimals: 4
    sample_duration: 900ms
    internal: true

  - platform: adc
    pin: A0
    id: adc_sensor
    update_interval: 10s
    internal: true
