---
<<: !include _common-esp8266.yml

# Enable wifi with static ip
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  fast_connect: true
  manual_ip:
    static_ip: 192.168.1.54
    gateway: 192.168.1.1
    subnet: 255.255.255.0

# Esphome setup
esphome:
  name: stove
  platform: ESP8266
  board: d1_mini

# Modules setup
binary_sensor:
  # TV Power Button with state from CT Clamp
  - platform: template
    name: Stove
    # starting the cooker hood +/- 0.31V (0.01A)
    lambda: |
      if (id(stove_clamp).state > 0.04) {
          return true;
      } else {
        return false;
      }

# CT Clamp sensor to check if the stove is on
sensor:
  - platform: ct_clamp
    sensor: adc_sensor
    id: stove_clamp
    update_interval: 10s
    accuracy_decimals: 4
    internal: true

  - platform: adc
    pin: A0
    id: adc_sensor
    update_interval: 10s
    internal: true
