---
<<: !include _common-esp32.yml

substitutions:
  devicename: watermeter
  wifi_ip: 192.168.1.55

sensor:
  - platform: pulse_counter
    pin:
      number: D1
      # mode: INPUT_PULLUP
    name: Water Meter
    unit_of_measurement: m3
    update_interval: 10s
    # internal_filter: 5us
    # filters:
    #   - multiply: 0.006  # 10000/min = 1m3
    accuracy_decimals: 4
    on_value:
      then:
        - switch.turn_on: led
        - delay: 100ms
        - switch.turn_off: led

switch:
  - platform: gpio
    pin: D5
    id: led
