---
<<: !include _common-esp32.yml

substitutions:
  devicename: baecon
  wifi_ip: 192.168.1.56

esp32_ble_tracker:
  scan_parameters:
    active: false  # not needed and consumes more power

binary_sensor:
  - platform: ble_presence
    device_class: occupancy
    ibeacon_uuid: !secret wilmar_ble_ibeacon_uuid
    name: Wilmar Phone Livingroom

  - platform: ble_presence
    device_class: occupancy
    ibeacon_uuid: !secret annemarie_ble_ibeacon_uuid
    name: Annemarie Phone Livingroom
