---
<<: !include _common-esp8266.yml
<<: !include _common-blind.yml

substitutions:
  wifi_ip: 192.168.1.59
  devicename: livingroom_blind_small
  upper_devicename: Livingroom Blind Small
  mystepper: my_stepper  # Name of the stepper motor (leave as is)
  speed: 1000 steps/s  # Set the speed of the motor
  inverted: "false"  # Invert when motor on left side of blinds
  reportin: "0" # Set if you want the blind to report position while moving (causes delay)
