---
<<: !include _common-esp8266.yml
<<: !include _common-blind.yml

substitutions:
  wifi_ip: 192.168.1.60
  devicename: dining_blind
  upper_devicename: Dining Blinds
  mystepper: my_stepper  # Name of the stepper motor (leave as is)
  speed: 1000 steps/s  # Set the speed of the motors
  inverted: "false"  # Invert when motor on left side of blinds
  reportin: "0" # Set if you want the blind to report position while moving (causes delay)
