---
esphome:
  name: baecon
  platform: ESP32
  board: esp32doit-devkit-v1

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: !secret api_password

ota:
  password: !secret ota_password

esp32_ble_beacon:
  type: iBeacon
  uuid: '55add50c-db10-4cc5-bc81-5635a379686f'
  major: 10123
  minor: 1
