esphome:
  name: kitchen_light
  platform: ESP8266
  board: d1

wifi:
  ssid: B3 Sm4rt
  # password: "test"

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: test

ota:
  password: test

binary_sensor:
  - platform: gpio
    pin:
      number: GPIO0
      mode: INPUT_PULLUP
      inverted: True
    name: Sonoff Basic Button
    on_press:
      - switch.toggle: relay

switch:
  - platform: gpio
    name: Sonoff Basic Relay
    pin: GPIO12
    id: relay

status_led:
  pin:
    number: GPIO13
    inverted: yes
